"""

Revision ID: 1805441597b7
Revises: f9bf76b38db9
Create Date: 2023-08-13 03:45:54.259527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1805441597b7'
down_revision: Union[str, None] = 'f9bf76b38db9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_metadata', sa.Column('document_fk', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'document_metadata', 'document', ['document_fk'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_metadata', type_='foreignkey')
    op.drop_column('document_metadata', 'document_fk')
    # ### end Alembic commands ###
