"""

Revision ID: 52181fa45150
Revises: c52b8a9c49af
Create Date: 2023-08-25 02:53:28.247630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52181fa45150'
down_revision: Union[str, None] = 'c52b8a9c49af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'document_metadata', ['drive_file_fk'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_metadata', type_='unique')
    # ### end Alembic commands ###
